version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo -n -e "BUILD_ENV=docker\nenvName=production\ninternalEndpointUrl=${INTERNAL_ENDPOINT_URL}\nexternalEndpointUrl=${EXTERNAL_ENDPOINT_URL}\n" > src/.env
      - docker-compose -f ./docker/docker-compose.yml build --no-cache
      - docker tag aws-ecr-sample-nginx:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}-nginx:${IMAGE_TAG}
      - docker tag aws-ecr-sample-webapp:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}-webapp:${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}-nginx:${IMAGE_TAG}
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}-webapp:${IMAGE_TAG}
      